# Generated by Django 2.2.28 on 2022-05-01 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apollModel',
            fields=[
                ('question', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='upollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('easy', 'easy'), ('tough', 'tough')], default='easy', max_length=5)),
                ('vote', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.apollModel')),
            ],
        ),
        migrations.CreateModel(
            name='tpollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('easy', 'easy'), ('tough', 'tough')], default='easy', max_length=5)),
                ('vote', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.apollModel')),
            ],
        ),
    ]
